version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/SourceGeneratorUtils" #SourceGeneratorUtils.csproj
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 5
  - package-ecosystem: "nuget"
    directory: "/tests/SourceGeneratorUtils.Tests" #SourceGeneratorUtils.Tests.csproj
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 5
