namespace SourceGeneratorUtils;

internal static class WellKnownStrings
{
    public const string enable = nameof(enable), disable = nameof(disable);
    public const string ShortSourcePrefix = "// <auto-generated/>";
    public const string GlobalAlias = "global::";
    public const string CommaWithSpace = ", ";
}