name: CI (main)

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"

  workflow_dispatch:

env:
  PACKAGE_ID: SourceGeneratorUtils
  
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: .NET Build & Test
    uses: ./.github/workflows/build.yml
    with:
        buildStaticSite: true
        packNugetPackage: true

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Download artifacts
        uses: actions/download-artifact@v3
      
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3

      - name: Push to GitHub Packages
        run: dotnet nuget push **/ci/*.nupkg -s https://nuget.pkg.github.com/thenameless314159/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
      
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: './docs/_site/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2