name: PRs

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"

  workflow_dispatch:

jobs:
  build:
    name: .NET Build & Test PR
    uses: ./.github/workflows/build.yml

  analyze:
        name: SonarCloud Analysis
        uses: ./.github/workflows/analysis.yml